const Params = {
  // Operations
  CREATE_KEY: "createKey",
  CREATE_PASS: "createPass",
  CREATE_HASH: "createHash",
  CREATE_HASH_CUSTOM: "createHashCustom",
  CHECK_HASH: "checkHash",
  CREATE_TOKEN: "createToken",
  CHECK_TOKEN: "checkToken",
  // Options
  ROUNDS: "rounds",
  LENGTH: "length",
  USERNAME: "username",
  PASS: "pass",
  HASH: "hash",
  SECRET_KEY: "secretKey",
  TOKEN: "token",
};

const ParamsConfig = {
  // Operations
  [Params.KEY]: {
    name: "createKey",
    describe: "Create a random key",
    type: "boolean",
    default: false,
  },
  [Params.CREATE_PASS]: {
    name: "createPass",
    describe: "Create a random password",
    type: "boolean",
    default: false,
  },
  [Params.CREATE_HASH]: {
    name: "createHash",
    describe: "Create pass - salt - hash",
    type: "boolean",
    default: false,
  },
  [Params.CREATE_HASH_CUSTOM]: {
    name: "createHashCustom",
    describe: "Create salt - hash from input pass",
    type: "boolean",
    default: false,
  },
  [Params.CHECK_HASH]: {
    name: "checkHash",
    describe: "Check hash from input pass - hash",
    type: "boolean",
    default: false,
  },
  [Params.CREATE_TOKEN]: {
    name: "createToken",
    describe: "Create token from input username - secret key",
    type: "boolean",
    default: false,
  },
  [Params.CHECK_TOKEN]: {
    name: "checkToken",
    describe: "Check token from token & secret",
    type: "boolean",
    default: false,
  },
  // Options
  [Params.LENGTH]: {
    name: "length",
    default: 12,
    describe: "Set the length for the autogenerated pass",
    type: "number",
  },
  [Params.ROUNDS]: {
    name: "rounds",
    default: 10,
    describe: "Set rounds for the autigen salt",
    type: "number",
  },
  [Params.USERNAME]: {
    name: "username",
    describe: "Set the username",
    type: "string",
  },
  [Params.PASS]: {
    name: "pass",
    describe: "Set the pass",
    type: "string",
  },
  [Params.HASH]: {
    name: "hash",
    describe: "Set the hash",
    type: "string",
  },
  [Params.SECRET_KEY]: {
    name: "secretKey",
    describe: "Set the secret key for the token",
    type: "string",
  },
  [Params.TOKEN]: {
    name: "token",
    describe: "Set the token",
    type: "string",
  },
};

export {Params, ParamsConfig};
